---
    - name: Install EPEL repository
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Create Nginx repo file
      become: true
      ansible.builtin.copy:
        content: |
          [nginx]
          name=nginx repo
          baseurl=https://nginx.org/packages/centos/7/$basearch/
          gpgcheck=0
          enabled=1
        dest: /etc/yum.repos.d/nginx.repo
        owner: root
        group: root
        mode: "0644"
    - name: Update YUM cache
      become: true
      ansible.builtin.yum:
        update_cache: true
    - name: Install Nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Install Git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
    - name: Configure Nginx
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Restart Nginx
    - name: Clone Lighthouse repository
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_url }}"
        dest: "{{ lighthouse_dir }}"
        version: master
        force: yes
    - name: Disable default Nginx site
      become: true
      ansible.builtin.file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
      notify: Restart Nginx    
    - name: Set correct permissions for Lighthouse
      become: true
      ansible.builtin.file:
        path: "{{ lighthouse_dir }}"
        state: directory
        owner: nginx
        group: nginx
        mode: "0755"
        recurse: yes
    - name: Configure Lighthouse Nginx site
      become: true
      ansible.builtin.template:
        src:  lighthouse.conf.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: "0644"
      notify: Restart Nginx
